version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  site:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mon_site
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
